task :default => :puma
desc "run stream.rb using puma server"
task :puma do
  sh "ruby stream.rb -e production -s puma"
end

desc "run stream.rb using thin server"
task :thin do
  sh "ruby stream.rb -e production -s thin"
end
